name: 🚀 Build and deploy container app to Azure Function App

on:
  push:
    branches:
      - y
    paths:
      - 'services/emails/**'
      - 'services/subscriptions/**'

jobs:
  common-steps:
    runs-on: 'ubuntu-latest'

    outputs:
      REPO: ${{ steps.downcase.outputs.lowercase }}
      TAG: ${{ steps.get_release.outputs.tag_name }}
      MATRIX: ${{ steps.determine_directories.outputs.changed_directories }}
      LABELS: ${{ steps.docker_meta.outputs.labels }}

    steps:
      - name: 📂 Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🔎 Determine modified directories
        id: determine_directories
        run: |   
          changed_files=$(git diff --name-only HEAD^ HEAD)
          paths=(
            'services/emails' 
            'services/subscriptions' 
          )
          declare -A changed_dirs=() 
          for file in $changed_files; do
            for path in "${paths[@]}"; do
              if [[ "$file" =~ ^$path/[^/]+ ]]; then
                dir=$(echo "$file" | cut -d'/' -f1,2,3) 
                changed_dirs["$dir"]=1 
              fi
            done
          done
          json_array=""
          for dir in "${!changed_dirs[@]}"; do
            json_array+="\"$dir\","
          done
          json_array="[${json_array%,}]" 
          echo "Changed directories: $json_array"
          echo "::set-output name=changed_directories::$json_array"

      - name: 🛠️ Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: 🔖 Get release tag name
        id: get_release
        uses: cardinalby/git-get-release-action@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          latest: true

      - name: 🔄 downcase REPO
        uses: ASzc/change-string-case-action@v1
        id: downcase
        with:
          string: ${{ github.repository }}

      - name: 🐳 Docker metadata
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ env.REPO }}/${{ matrix.directory }}
          tags: |
            type=semver,pattern={{major}}.{{minor}}.{{patch}},value=${{ steps.get_release.outputs.tag_name }}
            type=semver,pattern={{major}}.{{minor}},value=${{ steps.get_release.outputs.tag_name }}
            type=semver,pattern={{major}},value=${{ steps.get_release.outputs.tag_name }}

  build-and-deploy:
    runs-on: 'ubuntu-latest'
    needs: common-steps
    env:
      REPO: ${{ needs.common-steps.outputs.REPO }}
      TAG: ${{ needs.common-steps.outputs.TAG }}
      MATRIX: ${{ needs.common-steps.outputs.MATRIX }}
      LABELS: ${{ needs.common-steps.outputs.LABELS }}

    strategy:
      matrix:
        directory: ${{fromJson(needs.common-steps.outputs.MATRIX)}}

    steps:
      - name: 📂 Checkout repository
        uses: actions/checkout@v4
        
      - name: 🔑 Log in to registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 🔑 Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 🏗️ Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: ./${{ matrix.directory }}
          push: true
          tags: ghcr.io/${{ env.REPO }}-${{ steps.get-last-level.outputs.last_level }}:${{ env.TAG }}
          labels: ${{ env.LABELS }}
          file: ./${{ matrix.directory }}/Dockerfile

      - name: 🔄 Extract Last Directory Level
        id: get-last-level
        run: |
          LAST_LEVEL=$(echo ${{ matrix.directory }} | xargs -n 1 basename)
          echo "::set-output name=last_level::$LAST_LEVEL"

      - name: 🚀 Deploy to Azure Functions
        id: deploy-to-functions
        uses: Azure/functions-container-action@v1
        with:
          app-name: ${{ steps.get-last-level.outputs.last_level }}
          image: 'ghcr.io/${{ env.REPO }}-${{ steps.get-last-level.outputs.last_level }}:${{ env.TAG }}'
